version: '3.8'

services:
  server:
    build:
      context: . 
      dockerfile: dockerfiles/apache2.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./src/:/var/www/html
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
      